######################################
lilak/add       LKGETChannelViewer
lilak/add       LKPolygonPadPlane
lilak/add       LKPulseShapeAnalysisTask
#lilak/add       LKHTTrackingTask
lilak/add       LKEveTask
#lilak/print all
lilak/collect_par   ha
lilak/execute   0
######################################

detector_name pku

LKRun/Name             pku2025
LKRun/RunID            221
LKRun/InputPath        data_conv
LKRun/OutputPath       data_conv
LKRun/SearchRun        conv
LKRun/Tag              viewer
LKRun/EventCountForMessage 1
